// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpgga.proto

#ifndef PROTOBUF_gpgga_2eproto__INCLUDED
#define PROTOBUF_gpgga_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gnss_driver {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_gpgga_2eproto();
void protobuf_InitDefaults_gpgga_2eproto();
void protobuf_AssignDesc_gpgga_2eproto();
void protobuf_ShutdownFile_gpgga_2eproto();

class GPGGA;

// ===================================================================

class GPGGA : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gnss_driver.pb.GPGGA) */ {
 public:
  GPGGA();
  virtual ~GPGGA();

  GPGGA(const GPGGA& from);

  inline GPGGA& operator=(const GPGGA& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GPGGA& default_instance();

  static const GPGGA* internal_default_instance();

  void Swap(GPGGA* other);

  // implements Message ----------------------------------------------

  inline GPGGA* New() const { return New(NULL); }

  GPGGA* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GPGGA& from);
  void MergeFrom(const GPGGA& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GPGGA* other);
  void UnsafeMergeFrom(const GPGGA& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string gpgga = 1;
  bool has_gpgga() const;
  void clear_gpgga();
  static const int kGpggaFieldNumber = 1;
  const ::std::string& gpgga() const;
  void set_gpgga(const ::std::string& value);
  void set_gpgga(const char* value);
  void set_gpgga(const char* value, size_t size);
  ::std::string* mutable_gpgga();
  ::std::string* release_gpgga();
  void set_allocated_gpgga(::std::string* gpgga);

  // @@protoc_insertion_point(class_scope:gnss_driver.pb.GPGGA)
 private:
  inline void set_has_gpgga();
  inline void clear_has_gpgga();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr gpgga_;
  friend void  protobuf_InitDefaults_gpgga_2eproto_impl();
  friend void  protobuf_AddDesc_gpgga_2eproto_impl();
  friend void protobuf_AssignDesc_gpgga_2eproto();
  friend void protobuf_ShutdownFile_gpgga_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<GPGGA> GPGGA_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GPGGA

// required string gpgga = 1;
inline bool GPGGA::has_gpgga() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GPGGA::set_has_gpgga() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GPGGA::clear_has_gpgga() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GPGGA::clear_gpgga() {
  gpgga_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_gpgga();
}
inline const ::std::string& GPGGA::gpgga() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.GPGGA.gpgga)
  return gpgga_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GPGGA::set_gpgga(const ::std::string& value) {
  set_has_gpgga();
  gpgga_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gnss_driver.pb.GPGGA.gpgga)
}
inline void GPGGA::set_gpgga(const char* value) {
  set_has_gpgga();
  gpgga_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gnss_driver.pb.GPGGA.gpgga)
}
inline void GPGGA::set_gpgga(const char* value, size_t size) {
  set_has_gpgga();
  gpgga_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gnss_driver.pb.GPGGA.gpgga)
}
inline ::std::string* GPGGA::mutable_gpgga() {
  set_has_gpgga();
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.GPGGA.gpgga)
  return gpgga_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GPGGA::release_gpgga() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.GPGGA.gpgga)
  clear_has_gpgga();
  return gpgga_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GPGGA::set_allocated_gpgga(::std::string* gpgga) {
  if (gpgga != NULL) {
    set_has_gpgga();
  } else {
    clear_has_gpgga();
  }
  gpgga_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gpgga);
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.GPGGA.gpgga)
}

inline const GPGGA* GPGGA::internal_default_instance() {
  return &GPGGA_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace gnss_driver

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gpgga_2eproto__INCLUDED
