// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

#ifndef PROTOBUF_header_2eproto__INCLUDED
#define PROTOBUF_header_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "error_code.pb.h"
// @@protoc_insertion_point(includes)

namespace gnss_driver {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_header_2eproto();
void protobuf_InitDefaults_header_2eproto();
void protobuf_AssignDesc_header_2eproto();
void protobuf_ShutdownFile_header_2eproto();

class Header;

// ===================================================================

class Header : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gnss_driver.pb.Header) */ {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Header& default_instance();

  static const Header* internal_default_instance();

  void Swap(Header* other);

  // implements Message ----------------------------------------------

  inline Header* New() const { return New(NULL); }

  Header* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Header* other);
  void UnsafeMergeFrom(const Header& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double timestamp_sec = 1;
  bool has_timestamp_sec() const;
  void clear_timestamp_sec();
  static const int kTimestampSecFieldNumber = 1;
  double timestamp_sec() const;
  void set_timestamp_sec(double value);

  // optional string module_name = 2;
  bool has_module_name() const;
  void clear_module_name();
  static const int kModuleNameFieldNumber = 2;
  const ::std::string& module_name() const;
  void set_module_name(const ::std::string& value);
  void set_module_name(const char* value);
  void set_module_name(const char* value, size_t size);
  ::std::string* mutable_module_name();
  ::std::string* release_module_name();
  void set_allocated_module_name(::std::string* module_name);

  // optional uint32 sequence_num = 3;
  bool has_sequence_num() const;
  void clear_sequence_num();
  static const int kSequenceNumFieldNumber = 3;
  ::google::protobuf::uint32 sequence_num() const;
  void set_sequence_num(::google::protobuf::uint32 value);

  // optional uint64 lidar_timestamp = 4;
  bool has_lidar_timestamp() const;
  void clear_lidar_timestamp();
  static const int kLidarTimestampFieldNumber = 4;
  ::google::protobuf::uint64 lidar_timestamp() const;
  void set_lidar_timestamp(::google::protobuf::uint64 value);

  // optional uint64 camera_timestamp = 5;
  bool has_camera_timestamp() const;
  void clear_camera_timestamp();
  static const int kCameraTimestampFieldNumber = 5;
  ::google::protobuf::uint64 camera_timestamp() const;
  void set_camera_timestamp(::google::protobuf::uint64 value);

  // optional uint64 radar_timestamp = 6;
  bool has_radar_timestamp() const;
  void clear_radar_timestamp();
  static const int kRadarTimestampFieldNumber = 6;
  ::google::protobuf::uint64 radar_timestamp() const;
  void set_radar_timestamp(::google::protobuf::uint64 value);

  // optional uint32 version = 7 [default = 1];
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 7;
  ::google::protobuf::uint32 version() const;
  void set_version(::google::protobuf::uint32 value);

  // optional .gnss_driver.pb.StatusPb status = 8;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 8;
  const ::gnss_driver::pb::StatusPb& status() const;
  ::gnss_driver::pb::StatusPb* mutable_status();
  ::gnss_driver::pb::StatusPb* release_status();
  void set_allocated_status(::gnss_driver::pb::StatusPb* status);

  // @@protoc_insertion_point(class_scope:gnss_driver.pb.Header)
 private:
  inline void set_has_timestamp_sec();
  inline void clear_has_timestamp_sec();
  inline void set_has_module_name();
  inline void clear_has_module_name();
  inline void set_has_sequence_num();
  inline void clear_has_sequence_num();
  inline void set_has_lidar_timestamp();
  inline void clear_has_lidar_timestamp();
  inline void set_has_camera_timestamp();
  inline void clear_has_camera_timestamp();
  inline void set_has_radar_timestamp();
  inline void clear_has_radar_timestamp();
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr module_name_;
  ::gnss_driver::pb::StatusPb* status_;
  double timestamp_sec_;
  ::google::protobuf::uint64 lidar_timestamp_;
  ::google::protobuf::uint64 camera_timestamp_;
  ::google::protobuf::uint64 radar_timestamp_;
  ::google::protobuf::uint32 sequence_num_;
  ::google::protobuf::uint32 version_;
  friend void  protobuf_InitDefaults_header_2eproto_impl();
  friend void  protobuf_AddDesc_header_2eproto_impl();
  friend void protobuf_AssignDesc_header_2eproto();
  friend void protobuf_ShutdownFile_header_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Header> Header_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Header

// optional double timestamp_sec = 1;
inline bool Header::has_timestamp_sec() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Header::set_has_timestamp_sec() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Header::clear_has_timestamp_sec() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Header::clear_timestamp_sec() {
  timestamp_sec_ = 0;
  clear_has_timestamp_sec();
}
inline double Header::timestamp_sec() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Header.timestamp_sec)
  return timestamp_sec_;
}
inline void Header::set_timestamp_sec(double value) {
  set_has_timestamp_sec();
  timestamp_sec_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Header.timestamp_sec)
}

// optional string module_name = 2;
inline bool Header::has_module_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Header::set_has_module_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Header::clear_has_module_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Header::clear_module_name() {
  module_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_module_name();
}
inline const ::std::string& Header::module_name() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Header.module_name)
  return module_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_module_name(const ::std::string& value) {
  set_has_module_name();
  module_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Header.module_name)
}
inline void Header::set_module_name(const char* value) {
  set_has_module_name();
  module_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gnss_driver.pb.Header.module_name)
}
inline void Header::set_module_name(const char* value, size_t size) {
  set_has_module_name();
  module_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gnss_driver.pb.Header.module_name)
}
inline ::std::string* Header::mutable_module_name() {
  set_has_module_name();
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Header.module_name)
  return module_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Header::release_module_name() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Header.module_name)
  clear_has_module_name();
  return module_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_module_name(::std::string* module_name) {
  if (module_name != NULL) {
    set_has_module_name();
  } else {
    clear_has_module_name();
  }
  module_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), module_name);
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Header.module_name)
}

// optional uint32 sequence_num = 3;
inline bool Header::has_sequence_num() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Header::set_has_sequence_num() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Header::clear_has_sequence_num() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Header::clear_sequence_num() {
  sequence_num_ = 0u;
  clear_has_sequence_num();
}
inline ::google::protobuf::uint32 Header::sequence_num() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Header.sequence_num)
  return sequence_num_;
}
inline void Header::set_sequence_num(::google::protobuf::uint32 value) {
  set_has_sequence_num();
  sequence_num_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Header.sequence_num)
}

// optional uint64 lidar_timestamp = 4;
inline bool Header::has_lidar_timestamp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Header::set_has_lidar_timestamp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Header::clear_has_lidar_timestamp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Header::clear_lidar_timestamp() {
  lidar_timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_lidar_timestamp();
}
inline ::google::protobuf::uint64 Header::lidar_timestamp() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Header.lidar_timestamp)
  return lidar_timestamp_;
}
inline void Header::set_lidar_timestamp(::google::protobuf::uint64 value) {
  set_has_lidar_timestamp();
  lidar_timestamp_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Header.lidar_timestamp)
}

// optional uint64 camera_timestamp = 5;
inline bool Header::has_camera_timestamp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Header::set_has_camera_timestamp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Header::clear_has_camera_timestamp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Header::clear_camera_timestamp() {
  camera_timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_camera_timestamp();
}
inline ::google::protobuf::uint64 Header::camera_timestamp() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Header.camera_timestamp)
  return camera_timestamp_;
}
inline void Header::set_camera_timestamp(::google::protobuf::uint64 value) {
  set_has_camera_timestamp();
  camera_timestamp_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Header.camera_timestamp)
}

// optional uint64 radar_timestamp = 6;
inline bool Header::has_radar_timestamp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Header::set_has_radar_timestamp() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Header::clear_has_radar_timestamp() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Header::clear_radar_timestamp() {
  radar_timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_radar_timestamp();
}
inline ::google::protobuf::uint64 Header::radar_timestamp() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Header.radar_timestamp)
  return radar_timestamp_;
}
inline void Header::set_radar_timestamp(::google::protobuf::uint64 value) {
  set_has_radar_timestamp();
  radar_timestamp_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Header.radar_timestamp)
}

// optional uint32 version = 7 [default = 1];
inline bool Header::has_version() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Header::set_has_version() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Header::clear_has_version() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Header::clear_version() {
  version_ = 1u;
  clear_has_version();
}
inline ::google::protobuf::uint32 Header::version() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Header.version)
  return version_;
}
inline void Header::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Header.version)
}

// optional .gnss_driver.pb.StatusPb status = 8;
inline bool Header::has_status() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Header::set_has_status() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Header::clear_has_status() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Header::clear_status() {
  if (status_ != NULL) status_->::gnss_driver::pb::StatusPb::Clear();
  clear_has_status();
}
inline const ::gnss_driver::pb::StatusPb& Header::status() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Header.status)
  return status_ != NULL ? *status_
                         : *::gnss_driver::pb::StatusPb::internal_default_instance();
}
inline ::gnss_driver::pb::StatusPb* Header::mutable_status() {
  set_has_status();
  if (status_ == NULL) {
    status_ = new ::gnss_driver::pb::StatusPb;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Header.status)
  return status_;
}
inline ::gnss_driver::pb::StatusPb* Header::release_status() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Header.status)
  clear_has_status();
  ::gnss_driver::pb::StatusPb* temp = status_;
  status_ = NULL;
  return temp;
}
inline void Header::set_allocated_status(::gnss_driver::pb::StatusPb* status) {
  delete status_;
  status_ = status;
  if (status) {
    set_has_status();
  } else {
    clear_has_status();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Header.status)
}

inline const Header* Header::internal_default_instance() {
  return &Header_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace gnss_driver

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_header_2eproto__INCLUDED
