// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ins.proto

#ifndef PROTOBUF_ins_2eproto__INCLUDED
#define PROTOBUF_ins_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
#include "geometry.pb.h"
// @@protoc_insertion_point(includes)

namespace gnss_driver {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ins_2eproto();
void protobuf_InitDefaults_ins_2eproto();
void protobuf_AssignDesc_ins_2eproto();
void protobuf_ShutdownFile_ins_2eproto();

class Ins;

enum Ins_Type {
  Ins_Type_INVALID = 0,
  Ins_Type_CONVERGING = 1,
  Ins_Type_GOOD = 2
};
bool Ins_Type_IsValid(int value);
const Ins_Type Ins_Type_Type_MIN = Ins_Type_INVALID;
const Ins_Type Ins_Type_Type_MAX = Ins_Type_GOOD;
const int Ins_Type_Type_ARRAYSIZE = Ins_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Ins_Type_descriptor();
inline const ::std::string& Ins_Type_Name(Ins_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Ins_Type_descriptor(), value);
}
inline bool Ins_Type_Parse(
    const ::std::string& name, Ins_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Ins_Type>(
    Ins_Type_descriptor(), name, value);
}
// ===================================================================

class Ins : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gnss_driver.pb.Ins) */ {
 public:
  Ins();
  virtual ~Ins();

  Ins(const Ins& from);

  inline Ins& operator=(const Ins& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Ins& default_instance();

  static const Ins* internal_default_instance();

  void Swap(Ins* other);

  // implements Message ----------------------------------------------

  inline Ins* New() const { return New(NULL); }

  Ins* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Ins& from);
  void MergeFrom(const Ins& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Ins* other);
  void UnsafeMergeFrom(const Ins& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Ins_Type Type;
  static const Type INVALID =
    Ins_Type_INVALID;
  static const Type CONVERGING =
    Ins_Type_CONVERGING;
  static const Type GOOD =
    Ins_Type_GOOD;
  static inline bool Type_IsValid(int value) {
    return Ins_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Ins_Type_Type_MIN;
  static const Type Type_MAX =
    Ins_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Ins_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Ins_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Ins_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Ins_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .gnss_driver.pb.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::gnss_driver::pb::Header& header() const;
  ::gnss_driver::pb::Header* mutable_header();
  ::gnss_driver::pb::Header* release_header();
  void set_allocated_header(::gnss_driver::pb::Header* header);

  // optional double measurement_time = 2;
  bool has_measurement_time() const;
  void clear_measurement_time();
  static const int kMeasurementTimeFieldNumber = 2;
  double measurement_time() const;
  void set_measurement_time(double value);

  // optional .gnss_driver.pb.Ins.Type type = 3;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::gnss_driver::pb::Ins_Type type() const;
  void set_type(::gnss_driver::pb::Ins_Type value);

  // optional .gnss_driver.pb.PointLLH position = 4;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 4;
  const ::gnss_driver::pb::PointLLH& position() const;
  ::gnss_driver::pb::PointLLH* mutable_position();
  ::gnss_driver::pb::PointLLH* release_position();
  void set_allocated_position(::gnss_driver::pb::PointLLH* position);

  // optional .gnss_driver.pb.Point3D euler_angles = 5;
  bool has_euler_angles() const;
  void clear_euler_angles();
  static const int kEulerAnglesFieldNumber = 5;
  const ::gnss_driver::pb::Point3D& euler_angles() const;
  ::gnss_driver::pb::Point3D* mutable_euler_angles();
  ::gnss_driver::pb::Point3D* release_euler_angles();
  void set_allocated_euler_angles(::gnss_driver::pb::Point3D* euler_angles);

  // optional .gnss_driver.pb.Point3D linear_velocity = 6;
  bool has_linear_velocity() const;
  void clear_linear_velocity();
  static const int kLinearVelocityFieldNumber = 6;
  const ::gnss_driver::pb::Point3D& linear_velocity() const;
  ::gnss_driver::pb::Point3D* mutable_linear_velocity();
  ::gnss_driver::pb::Point3D* release_linear_velocity();
  void set_allocated_linear_velocity(::gnss_driver::pb::Point3D* linear_velocity);

  // optional .gnss_driver.pb.Point3D angular_velocity = 7;
  bool has_angular_velocity() const;
  void clear_angular_velocity();
  static const int kAngularVelocityFieldNumber = 7;
  const ::gnss_driver::pb::Point3D& angular_velocity() const;
  ::gnss_driver::pb::Point3D* mutable_angular_velocity();
  ::gnss_driver::pb::Point3D* release_angular_velocity();
  void set_allocated_angular_velocity(::gnss_driver::pb::Point3D* angular_velocity);

  // optional .gnss_driver.pb.Point3D linear_acceleration = 8;
  bool has_linear_acceleration() const;
  void clear_linear_acceleration();
  static const int kLinearAccelerationFieldNumber = 8;
  const ::gnss_driver::pb::Point3D& linear_acceleration() const;
  ::gnss_driver::pb::Point3D* mutable_linear_acceleration();
  ::gnss_driver::pb::Point3D* release_linear_acceleration();
  void set_allocated_linear_acceleration(::gnss_driver::pb::Point3D* linear_acceleration);

  // repeated float position_covariance = 9 [packed = true];
  int position_covariance_size() const;
  void clear_position_covariance();
  static const int kPositionCovarianceFieldNumber = 9;
  float position_covariance(int index) const;
  void set_position_covariance(int index, float value);
  void add_position_covariance(float value);
  const ::google::protobuf::RepeatedField< float >&
      position_covariance() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_position_covariance();

  // repeated float euler_angles_covariance = 10 [packed = true];
  int euler_angles_covariance_size() const;
  void clear_euler_angles_covariance();
  static const int kEulerAnglesCovarianceFieldNumber = 10;
  float euler_angles_covariance(int index) const;
  void set_euler_angles_covariance(int index, float value);
  void add_euler_angles_covariance(float value);
  const ::google::protobuf::RepeatedField< float >&
      euler_angles_covariance() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_euler_angles_covariance();

  // repeated float linear_velocity_covariance = 11 [packed = true];
  int linear_velocity_covariance_size() const;
  void clear_linear_velocity_covariance();
  static const int kLinearVelocityCovarianceFieldNumber = 11;
  float linear_velocity_covariance(int index) const;
  void set_linear_velocity_covariance(int index, float value);
  void add_linear_velocity_covariance(float value);
  const ::google::protobuf::RepeatedField< float >&
      linear_velocity_covariance() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_linear_velocity_covariance();

  // repeated float angular_velocity_covariance = 12 [packed = true];
  int angular_velocity_covariance_size() const;
  void clear_angular_velocity_covariance();
  static const int kAngularVelocityCovarianceFieldNumber = 12;
  float angular_velocity_covariance(int index) const;
  void set_angular_velocity_covariance(int index, float value);
  void add_angular_velocity_covariance(float value);
  const ::google::protobuf::RepeatedField< float >&
      angular_velocity_covariance() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_angular_velocity_covariance();

  // repeated float linear_acceleration_covariance = 13 [packed = true];
  int linear_acceleration_covariance_size() const;
  void clear_linear_acceleration_covariance();
  static const int kLinearAccelerationCovarianceFieldNumber = 13;
  float linear_acceleration_covariance(int index) const;
  void set_linear_acceleration_covariance(int index, float value);
  void add_linear_acceleration_covariance(float value);
  const ::google::protobuf::RepeatedField< float >&
      linear_acceleration_covariance() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_linear_acceleration_covariance();

  // @@protoc_insertion_point(class_scope:gnss_driver.pb.Ins)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_measurement_time();
  inline void clear_has_measurement_time();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_euler_angles();
  inline void clear_has_euler_angles();
  inline void set_has_linear_velocity();
  inline void clear_has_linear_velocity();
  inline void set_has_angular_velocity();
  inline void clear_has_angular_velocity();
  inline void set_has_linear_acceleration();
  inline void clear_has_linear_acceleration();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > position_covariance_;
  mutable int _position_covariance_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > euler_angles_covariance_;
  mutable int _euler_angles_covariance_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > linear_velocity_covariance_;
  mutable int _linear_velocity_covariance_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > angular_velocity_covariance_;
  mutable int _angular_velocity_covariance_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > linear_acceleration_covariance_;
  mutable int _linear_acceleration_covariance_cached_byte_size_;
  ::gnss_driver::pb::Header* header_;
  ::gnss_driver::pb::PointLLH* position_;
  ::gnss_driver::pb::Point3D* euler_angles_;
  ::gnss_driver::pb::Point3D* linear_velocity_;
  ::gnss_driver::pb::Point3D* angular_velocity_;
  ::gnss_driver::pb::Point3D* linear_acceleration_;
  double measurement_time_;
  int type_;
  friend void  protobuf_InitDefaults_ins_2eproto_impl();
  friend void  protobuf_AddDesc_ins_2eproto_impl();
  friend void protobuf_AssignDesc_ins_2eproto();
  friend void protobuf_ShutdownFile_ins_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Ins> Ins_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Ins

// optional .gnss_driver.pb.Header header = 1;
inline bool Ins::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Ins::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Ins::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Ins::clear_header() {
  if (header_ != NULL) header_->::gnss_driver::pb::Header::Clear();
  clear_has_header();
}
inline const ::gnss_driver::pb::Header& Ins::header() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.header)
  return header_ != NULL ? *header_
                         : *::gnss_driver::pb::Header::internal_default_instance();
}
inline ::gnss_driver::pb::Header* Ins::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::gnss_driver::pb::Header;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Ins.header)
  return header_;
}
inline ::gnss_driver::pb::Header* Ins::release_header() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Ins.header)
  clear_has_header();
  ::gnss_driver::pb::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void Ins::set_allocated_header(::gnss_driver::pb::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Ins.header)
}

// optional double measurement_time = 2;
inline bool Ins::has_measurement_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Ins::set_has_measurement_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Ins::clear_has_measurement_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Ins::clear_measurement_time() {
  measurement_time_ = 0;
  clear_has_measurement_time();
}
inline double Ins::measurement_time() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.measurement_time)
  return measurement_time_;
}
inline void Ins::set_measurement_time(double value) {
  set_has_measurement_time();
  measurement_time_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Ins.measurement_time)
}

// optional .gnss_driver.pb.Ins.Type type = 3;
inline bool Ins::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Ins::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Ins::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Ins::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::gnss_driver::pb::Ins_Type Ins::type() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.type)
  return static_cast< ::gnss_driver::pb::Ins_Type >(type_);
}
inline void Ins::set_type(::gnss_driver::pb::Ins_Type value) {
  assert(::gnss_driver::pb::Ins_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Ins.type)
}

// optional .gnss_driver.pb.PointLLH position = 4;
inline bool Ins::has_position() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Ins::set_has_position() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Ins::clear_has_position() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Ins::clear_position() {
  if (position_ != NULL) position_->::gnss_driver::pb::PointLLH::Clear();
  clear_has_position();
}
inline const ::gnss_driver::pb::PointLLH& Ins::position() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.position)
  return position_ != NULL ? *position_
                         : *::gnss_driver::pb::PointLLH::internal_default_instance();
}
inline ::gnss_driver::pb::PointLLH* Ins::mutable_position() {
  set_has_position();
  if (position_ == NULL) {
    position_ = new ::gnss_driver::pb::PointLLH;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Ins.position)
  return position_;
}
inline ::gnss_driver::pb::PointLLH* Ins::release_position() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Ins.position)
  clear_has_position();
  ::gnss_driver::pb::PointLLH* temp = position_;
  position_ = NULL;
  return temp;
}
inline void Ins::set_allocated_position(::gnss_driver::pb::PointLLH* position) {
  delete position_;
  position_ = position;
  if (position) {
    set_has_position();
  } else {
    clear_has_position();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Ins.position)
}

// optional .gnss_driver.pb.Point3D euler_angles = 5;
inline bool Ins::has_euler_angles() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Ins::set_has_euler_angles() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Ins::clear_has_euler_angles() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Ins::clear_euler_angles() {
  if (euler_angles_ != NULL) euler_angles_->::gnss_driver::pb::Point3D::Clear();
  clear_has_euler_angles();
}
inline const ::gnss_driver::pb::Point3D& Ins::euler_angles() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.euler_angles)
  return euler_angles_ != NULL ? *euler_angles_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
inline ::gnss_driver::pb::Point3D* Ins::mutable_euler_angles() {
  set_has_euler_angles();
  if (euler_angles_ == NULL) {
    euler_angles_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Ins.euler_angles)
  return euler_angles_;
}
inline ::gnss_driver::pb::Point3D* Ins::release_euler_angles() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Ins.euler_angles)
  clear_has_euler_angles();
  ::gnss_driver::pb::Point3D* temp = euler_angles_;
  euler_angles_ = NULL;
  return temp;
}
inline void Ins::set_allocated_euler_angles(::gnss_driver::pb::Point3D* euler_angles) {
  delete euler_angles_;
  euler_angles_ = euler_angles;
  if (euler_angles) {
    set_has_euler_angles();
  } else {
    clear_has_euler_angles();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Ins.euler_angles)
}

// optional .gnss_driver.pb.Point3D linear_velocity = 6;
inline bool Ins::has_linear_velocity() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Ins::set_has_linear_velocity() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Ins::clear_has_linear_velocity() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Ins::clear_linear_velocity() {
  if (linear_velocity_ != NULL) linear_velocity_->::gnss_driver::pb::Point3D::Clear();
  clear_has_linear_velocity();
}
inline const ::gnss_driver::pb::Point3D& Ins::linear_velocity() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.linear_velocity)
  return linear_velocity_ != NULL ? *linear_velocity_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
inline ::gnss_driver::pb::Point3D* Ins::mutable_linear_velocity() {
  set_has_linear_velocity();
  if (linear_velocity_ == NULL) {
    linear_velocity_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Ins.linear_velocity)
  return linear_velocity_;
}
inline ::gnss_driver::pb::Point3D* Ins::release_linear_velocity() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Ins.linear_velocity)
  clear_has_linear_velocity();
  ::gnss_driver::pb::Point3D* temp = linear_velocity_;
  linear_velocity_ = NULL;
  return temp;
}
inline void Ins::set_allocated_linear_velocity(::gnss_driver::pb::Point3D* linear_velocity) {
  delete linear_velocity_;
  linear_velocity_ = linear_velocity;
  if (linear_velocity) {
    set_has_linear_velocity();
  } else {
    clear_has_linear_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Ins.linear_velocity)
}

// optional .gnss_driver.pb.Point3D angular_velocity = 7;
inline bool Ins::has_angular_velocity() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Ins::set_has_angular_velocity() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Ins::clear_has_angular_velocity() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Ins::clear_angular_velocity() {
  if (angular_velocity_ != NULL) angular_velocity_->::gnss_driver::pb::Point3D::Clear();
  clear_has_angular_velocity();
}
inline const ::gnss_driver::pb::Point3D& Ins::angular_velocity() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.angular_velocity)
  return angular_velocity_ != NULL ? *angular_velocity_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
inline ::gnss_driver::pb::Point3D* Ins::mutable_angular_velocity() {
  set_has_angular_velocity();
  if (angular_velocity_ == NULL) {
    angular_velocity_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Ins.angular_velocity)
  return angular_velocity_;
}
inline ::gnss_driver::pb::Point3D* Ins::release_angular_velocity() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Ins.angular_velocity)
  clear_has_angular_velocity();
  ::gnss_driver::pb::Point3D* temp = angular_velocity_;
  angular_velocity_ = NULL;
  return temp;
}
inline void Ins::set_allocated_angular_velocity(::gnss_driver::pb::Point3D* angular_velocity) {
  delete angular_velocity_;
  angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    set_has_angular_velocity();
  } else {
    clear_has_angular_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Ins.angular_velocity)
}

// optional .gnss_driver.pb.Point3D linear_acceleration = 8;
inline bool Ins::has_linear_acceleration() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Ins::set_has_linear_acceleration() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Ins::clear_has_linear_acceleration() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Ins::clear_linear_acceleration() {
  if (linear_acceleration_ != NULL) linear_acceleration_->::gnss_driver::pb::Point3D::Clear();
  clear_has_linear_acceleration();
}
inline const ::gnss_driver::pb::Point3D& Ins::linear_acceleration() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.linear_acceleration)
  return linear_acceleration_ != NULL ? *linear_acceleration_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
inline ::gnss_driver::pb::Point3D* Ins::mutable_linear_acceleration() {
  set_has_linear_acceleration();
  if (linear_acceleration_ == NULL) {
    linear_acceleration_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Ins.linear_acceleration)
  return linear_acceleration_;
}
inline ::gnss_driver::pb::Point3D* Ins::release_linear_acceleration() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Ins.linear_acceleration)
  clear_has_linear_acceleration();
  ::gnss_driver::pb::Point3D* temp = linear_acceleration_;
  linear_acceleration_ = NULL;
  return temp;
}
inline void Ins::set_allocated_linear_acceleration(::gnss_driver::pb::Point3D* linear_acceleration) {
  delete linear_acceleration_;
  linear_acceleration_ = linear_acceleration;
  if (linear_acceleration) {
    set_has_linear_acceleration();
  } else {
    clear_has_linear_acceleration();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Ins.linear_acceleration)
}

// repeated float position_covariance = 9 [packed = true];
inline int Ins::position_covariance_size() const {
  return position_covariance_.size();
}
inline void Ins::clear_position_covariance() {
  position_covariance_.Clear();
}
inline float Ins::position_covariance(int index) const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.position_covariance)
  return position_covariance_.Get(index);
}
inline void Ins::set_position_covariance(int index, float value) {
  position_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Ins.position_covariance)
}
inline void Ins::add_position_covariance(float value) {
  position_covariance_.Add(value);
  // @@protoc_insertion_point(field_add:gnss_driver.pb.Ins.position_covariance)
}
inline const ::google::protobuf::RepeatedField< float >&
Ins::position_covariance() const {
  // @@protoc_insertion_point(field_list:gnss_driver.pb.Ins.position_covariance)
  return position_covariance_;
}
inline ::google::protobuf::RepeatedField< float >*
Ins::mutable_position_covariance() {
  // @@protoc_insertion_point(field_mutable_list:gnss_driver.pb.Ins.position_covariance)
  return &position_covariance_;
}

// repeated float euler_angles_covariance = 10 [packed = true];
inline int Ins::euler_angles_covariance_size() const {
  return euler_angles_covariance_.size();
}
inline void Ins::clear_euler_angles_covariance() {
  euler_angles_covariance_.Clear();
}
inline float Ins::euler_angles_covariance(int index) const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.euler_angles_covariance)
  return euler_angles_covariance_.Get(index);
}
inline void Ins::set_euler_angles_covariance(int index, float value) {
  euler_angles_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Ins.euler_angles_covariance)
}
inline void Ins::add_euler_angles_covariance(float value) {
  euler_angles_covariance_.Add(value);
  // @@protoc_insertion_point(field_add:gnss_driver.pb.Ins.euler_angles_covariance)
}
inline const ::google::protobuf::RepeatedField< float >&
Ins::euler_angles_covariance() const {
  // @@protoc_insertion_point(field_list:gnss_driver.pb.Ins.euler_angles_covariance)
  return euler_angles_covariance_;
}
inline ::google::protobuf::RepeatedField< float >*
Ins::mutable_euler_angles_covariance() {
  // @@protoc_insertion_point(field_mutable_list:gnss_driver.pb.Ins.euler_angles_covariance)
  return &euler_angles_covariance_;
}

// repeated float linear_velocity_covariance = 11 [packed = true];
inline int Ins::linear_velocity_covariance_size() const {
  return linear_velocity_covariance_.size();
}
inline void Ins::clear_linear_velocity_covariance() {
  linear_velocity_covariance_.Clear();
}
inline float Ins::linear_velocity_covariance(int index) const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.linear_velocity_covariance)
  return linear_velocity_covariance_.Get(index);
}
inline void Ins::set_linear_velocity_covariance(int index, float value) {
  linear_velocity_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Ins.linear_velocity_covariance)
}
inline void Ins::add_linear_velocity_covariance(float value) {
  linear_velocity_covariance_.Add(value);
  // @@protoc_insertion_point(field_add:gnss_driver.pb.Ins.linear_velocity_covariance)
}
inline const ::google::protobuf::RepeatedField< float >&
Ins::linear_velocity_covariance() const {
  // @@protoc_insertion_point(field_list:gnss_driver.pb.Ins.linear_velocity_covariance)
  return linear_velocity_covariance_;
}
inline ::google::protobuf::RepeatedField< float >*
Ins::mutable_linear_velocity_covariance() {
  // @@protoc_insertion_point(field_mutable_list:gnss_driver.pb.Ins.linear_velocity_covariance)
  return &linear_velocity_covariance_;
}

// repeated float angular_velocity_covariance = 12 [packed = true];
inline int Ins::angular_velocity_covariance_size() const {
  return angular_velocity_covariance_.size();
}
inline void Ins::clear_angular_velocity_covariance() {
  angular_velocity_covariance_.Clear();
}
inline float Ins::angular_velocity_covariance(int index) const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.angular_velocity_covariance)
  return angular_velocity_covariance_.Get(index);
}
inline void Ins::set_angular_velocity_covariance(int index, float value) {
  angular_velocity_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Ins.angular_velocity_covariance)
}
inline void Ins::add_angular_velocity_covariance(float value) {
  angular_velocity_covariance_.Add(value);
  // @@protoc_insertion_point(field_add:gnss_driver.pb.Ins.angular_velocity_covariance)
}
inline const ::google::protobuf::RepeatedField< float >&
Ins::angular_velocity_covariance() const {
  // @@protoc_insertion_point(field_list:gnss_driver.pb.Ins.angular_velocity_covariance)
  return angular_velocity_covariance_;
}
inline ::google::protobuf::RepeatedField< float >*
Ins::mutable_angular_velocity_covariance() {
  // @@protoc_insertion_point(field_mutable_list:gnss_driver.pb.Ins.angular_velocity_covariance)
  return &angular_velocity_covariance_;
}

// repeated float linear_acceleration_covariance = 13 [packed = true];
inline int Ins::linear_acceleration_covariance_size() const {
  return linear_acceleration_covariance_.size();
}
inline void Ins::clear_linear_acceleration_covariance() {
  linear_acceleration_covariance_.Clear();
}
inline float Ins::linear_acceleration_covariance(int index) const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Ins.linear_acceleration_covariance)
  return linear_acceleration_covariance_.Get(index);
}
inline void Ins::set_linear_acceleration_covariance(int index, float value) {
  linear_acceleration_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Ins.linear_acceleration_covariance)
}
inline void Ins::add_linear_acceleration_covariance(float value) {
  linear_acceleration_covariance_.Add(value);
  // @@protoc_insertion_point(field_add:gnss_driver.pb.Ins.linear_acceleration_covariance)
}
inline const ::google::protobuf::RepeatedField< float >&
Ins::linear_acceleration_covariance() const {
  // @@protoc_insertion_point(field_list:gnss_driver.pb.Ins.linear_acceleration_covariance)
  return linear_acceleration_covariance_;
}
inline ::google::protobuf::RepeatedField< float >*
Ins::mutable_linear_acceleration_covariance() {
  // @@protoc_insertion_point(field_mutable_list:gnss_driver.pb.Ins.linear_acceleration_covariance)
  return &linear_acceleration_covariance_;
}

inline const Ins* Ins::internal_default_instance() {
  return &Ins_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace gnss_driver

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::gnss_driver::pb::Ins_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gnss_driver::pb::Ins_Type>() {
  return ::gnss_driver::pb::Ins_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ins_2eproto__INCLUDED
