// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

#ifndef PROTOBUF_pose_2eproto__INCLUDED
#define PROTOBUF_pose_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "geometry.pb.h"
// @@protoc_insertion_point(includes)

namespace gnss_driver {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_pose_2eproto();
void protobuf_InitDefaults_pose_2eproto();
void protobuf_AssignDesc_pose_2eproto();
void protobuf_ShutdownFile_pose_2eproto();

class Pose;

// ===================================================================

class Pose : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gnss_driver.pb.Pose) */ {
 public:
  Pose();
  virtual ~Pose();

  Pose(const Pose& from);

  inline Pose& operator=(const Pose& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Pose& default_instance();

  static const Pose* internal_default_instance();

  void Swap(Pose* other);

  // implements Message ----------------------------------------------

  inline Pose* New() const { return New(NULL); }

  Pose* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Pose& from);
  void MergeFrom(const Pose& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Pose* other);
  void UnsafeMergeFrom(const Pose& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .gnss_driver.pb.PointENU position = 1;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 1;
  const ::gnss_driver::pb::PointENU& position() const;
  ::gnss_driver::pb::PointENU* mutable_position();
  ::gnss_driver::pb::PointENU* release_position();
  void set_allocated_position(::gnss_driver::pb::PointENU* position);

  // optional .gnss_driver.pb.Quaternion orientation = 2;
  bool has_orientation() const;
  void clear_orientation();
  static const int kOrientationFieldNumber = 2;
  const ::gnss_driver::pb::Quaternion& orientation() const;
  ::gnss_driver::pb::Quaternion* mutable_orientation();
  ::gnss_driver::pb::Quaternion* release_orientation();
  void set_allocated_orientation(::gnss_driver::pb::Quaternion* orientation);

  // optional .gnss_driver.pb.Point3D linear_velocity = 3;
  bool has_linear_velocity() const;
  void clear_linear_velocity();
  static const int kLinearVelocityFieldNumber = 3;
  const ::gnss_driver::pb::Point3D& linear_velocity() const;
  ::gnss_driver::pb::Point3D* mutable_linear_velocity();
  ::gnss_driver::pb::Point3D* release_linear_velocity();
  void set_allocated_linear_velocity(::gnss_driver::pb::Point3D* linear_velocity);

  // optional .gnss_driver.pb.Point3D linear_acceleration = 4;
  bool has_linear_acceleration() const;
  void clear_linear_acceleration();
  static const int kLinearAccelerationFieldNumber = 4;
  const ::gnss_driver::pb::Point3D& linear_acceleration() const;
  ::gnss_driver::pb::Point3D* mutable_linear_acceleration();
  ::gnss_driver::pb::Point3D* release_linear_acceleration();
  void set_allocated_linear_acceleration(::gnss_driver::pb::Point3D* linear_acceleration);

  // optional .gnss_driver.pb.Point3D angular_velocity = 5;
  bool has_angular_velocity() const;
  void clear_angular_velocity();
  static const int kAngularVelocityFieldNumber = 5;
  const ::gnss_driver::pb::Point3D& angular_velocity() const;
  ::gnss_driver::pb::Point3D* mutable_angular_velocity();
  ::gnss_driver::pb::Point3D* release_angular_velocity();
  void set_allocated_angular_velocity(::gnss_driver::pb::Point3D* angular_velocity);

  // optional double heading = 6;
  bool has_heading() const;
  void clear_heading();
  static const int kHeadingFieldNumber = 6;
  double heading() const;
  void set_heading(double value);

  // optional .gnss_driver.pb.Point3D linear_acceleration_vrf = 7;
  bool has_linear_acceleration_vrf() const;
  void clear_linear_acceleration_vrf();
  static const int kLinearAccelerationVrfFieldNumber = 7;
  const ::gnss_driver::pb::Point3D& linear_acceleration_vrf() const;
  ::gnss_driver::pb::Point3D* mutable_linear_acceleration_vrf();
  ::gnss_driver::pb::Point3D* release_linear_acceleration_vrf();
  void set_allocated_linear_acceleration_vrf(::gnss_driver::pb::Point3D* linear_acceleration_vrf);

  // optional .gnss_driver.pb.Point3D angular_velocity_vrf = 8;
  bool has_angular_velocity_vrf() const;
  void clear_angular_velocity_vrf();
  static const int kAngularVelocityVrfFieldNumber = 8;
  const ::gnss_driver::pb::Point3D& angular_velocity_vrf() const;
  ::gnss_driver::pb::Point3D* mutable_angular_velocity_vrf();
  ::gnss_driver::pb::Point3D* release_angular_velocity_vrf();
  void set_allocated_angular_velocity_vrf(::gnss_driver::pb::Point3D* angular_velocity_vrf);

  // @@protoc_insertion_point(class_scope:gnss_driver.pb.Pose)
 private:
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_orientation();
  inline void clear_has_orientation();
  inline void set_has_linear_velocity();
  inline void clear_has_linear_velocity();
  inline void set_has_linear_acceleration();
  inline void clear_has_linear_acceleration();
  inline void set_has_angular_velocity();
  inline void clear_has_angular_velocity();
  inline void set_has_heading();
  inline void clear_has_heading();
  inline void set_has_linear_acceleration_vrf();
  inline void clear_has_linear_acceleration_vrf();
  inline void set_has_angular_velocity_vrf();
  inline void clear_has_angular_velocity_vrf();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::gnss_driver::pb::PointENU* position_;
  ::gnss_driver::pb::Quaternion* orientation_;
  ::gnss_driver::pb::Point3D* linear_velocity_;
  ::gnss_driver::pb::Point3D* linear_acceleration_;
  ::gnss_driver::pb::Point3D* angular_velocity_;
  ::gnss_driver::pb::Point3D* linear_acceleration_vrf_;
  ::gnss_driver::pb::Point3D* angular_velocity_vrf_;
  double heading_;
  friend void  protobuf_InitDefaults_pose_2eproto_impl();
  friend void  protobuf_AddDesc_pose_2eproto_impl();
  friend void protobuf_AssignDesc_pose_2eproto();
  friend void protobuf_ShutdownFile_pose_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Pose> Pose_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Pose

// optional .gnss_driver.pb.PointENU position = 1;
inline bool Pose::has_position() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Pose::set_has_position() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Pose::clear_has_position() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Pose::clear_position() {
  if (position_ != NULL) position_->::gnss_driver::pb::PointENU::Clear();
  clear_has_position();
}
inline const ::gnss_driver::pb::PointENU& Pose::position() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.position)
  return position_ != NULL ? *position_
                         : *::gnss_driver::pb::PointENU::internal_default_instance();
}
inline ::gnss_driver::pb::PointENU* Pose::mutable_position() {
  set_has_position();
  if (position_ == NULL) {
    position_ = new ::gnss_driver::pb::PointENU;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.position)
  return position_;
}
inline ::gnss_driver::pb::PointENU* Pose::release_position() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.position)
  clear_has_position();
  ::gnss_driver::pb::PointENU* temp = position_;
  position_ = NULL;
  return temp;
}
inline void Pose::set_allocated_position(::gnss_driver::pb::PointENU* position) {
  delete position_;
  position_ = position;
  if (position) {
    set_has_position();
  } else {
    clear_has_position();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.position)
}

// optional .gnss_driver.pb.Quaternion orientation = 2;
inline bool Pose::has_orientation() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Pose::set_has_orientation() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Pose::clear_has_orientation() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Pose::clear_orientation() {
  if (orientation_ != NULL) orientation_->::gnss_driver::pb::Quaternion::Clear();
  clear_has_orientation();
}
inline const ::gnss_driver::pb::Quaternion& Pose::orientation() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.orientation)
  return orientation_ != NULL ? *orientation_
                         : *::gnss_driver::pb::Quaternion::internal_default_instance();
}
inline ::gnss_driver::pb::Quaternion* Pose::mutable_orientation() {
  set_has_orientation();
  if (orientation_ == NULL) {
    orientation_ = new ::gnss_driver::pb::Quaternion;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.orientation)
  return orientation_;
}
inline ::gnss_driver::pb::Quaternion* Pose::release_orientation() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.orientation)
  clear_has_orientation();
  ::gnss_driver::pb::Quaternion* temp = orientation_;
  orientation_ = NULL;
  return temp;
}
inline void Pose::set_allocated_orientation(::gnss_driver::pb::Quaternion* orientation) {
  delete orientation_;
  orientation_ = orientation;
  if (orientation) {
    set_has_orientation();
  } else {
    clear_has_orientation();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.orientation)
}

// optional .gnss_driver.pb.Point3D linear_velocity = 3;
inline bool Pose::has_linear_velocity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Pose::set_has_linear_velocity() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Pose::clear_has_linear_velocity() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Pose::clear_linear_velocity() {
  if (linear_velocity_ != NULL) linear_velocity_->::gnss_driver::pb::Point3D::Clear();
  clear_has_linear_velocity();
}
inline const ::gnss_driver::pb::Point3D& Pose::linear_velocity() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.linear_velocity)
  return linear_velocity_ != NULL ? *linear_velocity_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
inline ::gnss_driver::pb::Point3D* Pose::mutable_linear_velocity() {
  set_has_linear_velocity();
  if (linear_velocity_ == NULL) {
    linear_velocity_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.linear_velocity)
  return linear_velocity_;
}
inline ::gnss_driver::pb::Point3D* Pose::release_linear_velocity() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.linear_velocity)
  clear_has_linear_velocity();
  ::gnss_driver::pb::Point3D* temp = linear_velocity_;
  linear_velocity_ = NULL;
  return temp;
}
inline void Pose::set_allocated_linear_velocity(::gnss_driver::pb::Point3D* linear_velocity) {
  delete linear_velocity_;
  linear_velocity_ = linear_velocity;
  if (linear_velocity) {
    set_has_linear_velocity();
  } else {
    clear_has_linear_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.linear_velocity)
}

// optional .gnss_driver.pb.Point3D linear_acceleration = 4;
inline bool Pose::has_linear_acceleration() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Pose::set_has_linear_acceleration() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Pose::clear_has_linear_acceleration() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Pose::clear_linear_acceleration() {
  if (linear_acceleration_ != NULL) linear_acceleration_->::gnss_driver::pb::Point3D::Clear();
  clear_has_linear_acceleration();
}
inline const ::gnss_driver::pb::Point3D& Pose::linear_acceleration() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.linear_acceleration)
  return linear_acceleration_ != NULL ? *linear_acceleration_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
inline ::gnss_driver::pb::Point3D* Pose::mutable_linear_acceleration() {
  set_has_linear_acceleration();
  if (linear_acceleration_ == NULL) {
    linear_acceleration_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.linear_acceleration)
  return linear_acceleration_;
}
inline ::gnss_driver::pb::Point3D* Pose::release_linear_acceleration() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.linear_acceleration)
  clear_has_linear_acceleration();
  ::gnss_driver::pb::Point3D* temp = linear_acceleration_;
  linear_acceleration_ = NULL;
  return temp;
}
inline void Pose::set_allocated_linear_acceleration(::gnss_driver::pb::Point3D* linear_acceleration) {
  delete linear_acceleration_;
  linear_acceleration_ = linear_acceleration;
  if (linear_acceleration) {
    set_has_linear_acceleration();
  } else {
    clear_has_linear_acceleration();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.linear_acceleration)
}

// optional .gnss_driver.pb.Point3D angular_velocity = 5;
inline bool Pose::has_angular_velocity() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Pose::set_has_angular_velocity() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Pose::clear_has_angular_velocity() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Pose::clear_angular_velocity() {
  if (angular_velocity_ != NULL) angular_velocity_->::gnss_driver::pb::Point3D::Clear();
  clear_has_angular_velocity();
}
inline const ::gnss_driver::pb::Point3D& Pose::angular_velocity() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.angular_velocity)
  return angular_velocity_ != NULL ? *angular_velocity_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
inline ::gnss_driver::pb::Point3D* Pose::mutable_angular_velocity() {
  set_has_angular_velocity();
  if (angular_velocity_ == NULL) {
    angular_velocity_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.angular_velocity)
  return angular_velocity_;
}
inline ::gnss_driver::pb::Point3D* Pose::release_angular_velocity() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.angular_velocity)
  clear_has_angular_velocity();
  ::gnss_driver::pb::Point3D* temp = angular_velocity_;
  angular_velocity_ = NULL;
  return temp;
}
inline void Pose::set_allocated_angular_velocity(::gnss_driver::pb::Point3D* angular_velocity) {
  delete angular_velocity_;
  angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    set_has_angular_velocity();
  } else {
    clear_has_angular_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.angular_velocity)
}

// optional double heading = 6;
inline bool Pose::has_heading() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Pose::set_has_heading() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Pose::clear_has_heading() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Pose::clear_heading() {
  heading_ = 0;
  clear_has_heading();
}
inline double Pose::heading() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.heading)
  return heading_;
}
inline void Pose::set_heading(double value) {
  set_has_heading();
  heading_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Pose.heading)
}

// optional .gnss_driver.pb.Point3D linear_acceleration_vrf = 7;
inline bool Pose::has_linear_acceleration_vrf() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Pose::set_has_linear_acceleration_vrf() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Pose::clear_has_linear_acceleration_vrf() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Pose::clear_linear_acceleration_vrf() {
  if (linear_acceleration_vrf_ != NULL) linear_acceleration_vrf_->::gnss_driver::pb::Point3D::Clear();
  clear_has_linear_acceleration_vrf();
}
inline const ::gnss_driver::pb::Point3D& Pose::linear_acceleration_vrf() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.linear_acceleration_vrf)
  return linear_acceleration_vrf_ != NULL ? *linear_acceleration_vrf_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
inline ::gnss_driver::pb::Point3D* Pose::mutable_linear_acceleration_vrf() {
  set_has_linear_acceleration_vrf();
  if (linear_acceleration_vrf_ == NULL) {
    linear_acceleration_vrf_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.linear_acceleration_vrf)
  return linear_acceleration_vrf_;
}
inline ::gnss_driver::pb::Point3D* Pose::release_linear_acceleration_vrf() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.linear_acceleration_vrf)
  clear_has_linear_acceleration_vrf();
  ::gnss_driver::pb::Point3D* temp = linear_acceleration_vrf_;
  linear_acceleration_vrf_ = NULL;
  return temp;
}
inline void Pose::set_allocated_linear_acceleration_vrf(::gnss_driver::pb::Point3D* linear_acceleration_vrf) {
  delete linear_acceleration_vrf_;
  linear_acceleration_vrf_ = linear_acceleration_vrf;
  if (linear_acceleration_vrf) {
    set_has_linear_acceleration_vrf();
  } else {
    clear_has_linear_acceleration_vrf();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.linear_acceleration_vrf)
}

// optional .gnss_driver.pb.Point3D angular_velocity_vrf = 8;
inline bool Pose::has_angular_velocity_vrf() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Pose::set_has_angular_velocity_vrf() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Pose::clear_has_angular_velocity_vrf() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Pose::clear_angular_velocity_vrf() {
  if (angular_velocity_vrf_ != NULL) angular_velocity_vrf_->::gnss_driver::pb::Point3D::Clear();
  clear_has_angular_velocity_vrf();
}
inline const ::gnss_driver::pb::Point3D& Pose::angular_velocity_vrf() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.angular_velocity_vrf)
  return angular_velocity_vrf_ != NULL ? *angular_velocity_vrf_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
inline ::gnss_driver::pb::Point3D* Pose::mutable_angular_velocity_vrf() {
  set_has_angular_velocity_vrf();
  if (angular_velocity_vrf_ == NULL) {
    angular_velocity_vrf_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.angular_velocity_vrf)
  return angular_velocity_vrf_;
}
inline ::gnss_driver::pb::Point3D* Pose::release_angular_velocity_vrf() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.angular_velocity_vrf)
  clear_has_angular_velocity_vrf();
  ::gnss_driver::pb::Point3D* temp = angular_velocity_vrf_;
  angular_velocity_vrf_ = NULL;
  return temp;
}
inline void Pose::set_allocated_angular_velocity_vrf(::gnss_driver::pb::Point3D* angular_velocity_vrf) {
  delete angular_velocity_vrf_;
  angular_velocity_vrf_ = angular_velocity_vrf;
  if (angular_velocity_vrf) {
    set_has_angular_velocity_vrf();
  } else {
    clear_has_angular_velocity_vrf();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.angular_velocity_vrf)
}

inline const Pose* Pose::internal_default_instance() {
  return &Pose_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace gnss_driver

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pose_2eproto__INCLUDED
