// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pose.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gnss_driver {
namespace pb {

namespace {

const ::google::protobuf::Descriptor* Pose_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Pose_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_pose_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_pose_2eproto() {
  protobuf_AddDesc_pose_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pose.proto");
  GOOGLE_CHECK(file != NULL);
  Pose_descriptor_ = file->message_type(0);
  static const int Pose_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose, position_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose, orientation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose, linear_velocity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose, linear_acceleration_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose, angular_velocity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose, heading_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose, linear_acceleration_vrf_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose, angular_velocity_vrf_),
  };
  Pose_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Pose_descriptor_,
      Pose::internal_default_instance(),
      Pose_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose, _has_bits_),
      -1,
      -1,
      sizeof(Pose),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pose, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pose_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Pose_descriptor_, Pose::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_pose_2eproto() {
  Pose_default_instance_.Shutdown();
  delete Pose_reflection_;
}

void protobuf_InitDefaults_pose_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::gnss_driver::pb::protobuf_InitDefaults_geometry_2eproto();
  Pose_default_instance_.DefaultConstruct();
  Pose_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_pose_2eproto_once_);
void protobuf_InitDefaults_pose_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_pose_2eproto_once_,
                 &protobuf_InitDefaults_pose_2eproto_impl);
}
void protobuf_AddDesc_pose_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_pose_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\npose.proto\022\016gnss_driver.pb\032\016geometry.p"
    "roto\"\200\003\n\004Pose\022*\n\010position\030\001 \001(\0132\030.gnss_d"
    "river.pb.PointENU\022/\n\013orientation\030\002 \001(\0132\032"
    ".gnss_driver.pb.Quaternion\0220\n\017linear_vel"
    "ocity\030\003 \001(\0132\027.gnss_driver.pb.Point3D\0224\n\023"
    "linear_acceleration\030\004 \001(\0132\027.gnss_driver."
    "pb.Point3D\0221\n\020angular_velocity\030\005 \001(\0132\027.g"
    "nss_driver.pb.Point3D\022\017\n\007heading\030\006 \001(\001\0228"
    "\n\027linear_acceleration_vrf\030\007 \001(\0132\027.gnss_d"
    "river.pb.Point3D\0225\n\024angular_velocity_vrf"
    "\030\010 \001(\0132\027.gnss_driver.pb.Point3D", 431);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pose.proto", &protobuf_RegisterTypes);
  ::gnss_driver::pb::protobuf_AddDesc_geometry_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pose_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_pose_2eproto_once_);
void protobuf_AddDesc_pose_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_pose_2eproto_once_,
                 &protobuf_AddDesc_pose_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pose_2eproto {
  StaticDescriptorInitializer_pose_2eproto() {
    protobuf_AddDesc_pose_2eproto();
  }
} static_descriptor_initializer_pose_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Pose::kPositionFieldNumber;
const int Pose::kOrientationFieldNumber;
const int Pose::kLinearVelocityFieldNumber;
const int Pose::kLinearAccelerationFieldNumber;
const int Pose::kAngularVelocityFieldNumber;
const int Pose::kHeadingFieldNumber;
const int Pose::kLinearAccelerationVrfFieldNumber;
const int Pose::kAngularVelocityVrfFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Pose::Pose()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_pose_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:gnss_driver.pb.Pose)
}

void Pose::InitAsDefaultInstance() {
  position_ = const_cast< ::gnss_driver::pb::PointENU*>(
      ::gnss_driver::pb::PointENU::internal_default_instance());
  orientation_ = const_cast< ::gnss_driver::pb::Quaternion*>(
      ::gnss_driver::pb::Quaternion::internal_default_instance());
  linear_velocity_ = const_cast< ::gnss_driver::pb::Point3D*>(
      ::gnss_driver::pb::Point3D::internal_default_instance());
  linear_acceleration_ = const_cast< ::gnss_driver::pb::Point3D*>(
      ::gnss_driver::pb::Point3D::internal_default_instance());
  angular_velocity_ = const_cast< ::gnss_driver::pb::Point3D*>(
      ::gnss_driver::pb::Point3D::internal_default_instance());
  linear_acceleration_vrf_ = const_cast< ::gnss_driver::pb::Point3D*>(
      ::gnss_driver::pb::Point3D::internal_default_instance());
  angular_velocity_vrf_ = const_cast< ::gnss_driver::pb::Point3D*>(
      ::gnss_driver::pb::Point3D::internal_default_instance());
}

Pose::Pose(const Pose& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gnss_driver.pb.Pose)
}

void Pose::SharedCtor() {
  _cached_size_ = 0;
  position_ = NULL;
  orientation_ = NULL;
  linear_velocity_ = NULL;
  linear_acceleration_ = NULL;
  angular_velocity_ = NULL;
  linear_acceleration_vrf_ = NULL;
  angular_velocity_vrf_ = NULL;
  heading_ = 0;
}

Pose::~Pose() {
  // @@protoc_insertion_point(destructor:gnss_driver.pb.Pose)
  SharedDtor();
}

void Pose::SharedDtor() {
  if (this != &Pose_default_instance_.get()) {
    delete position_;
    delete orientation_;
    delete linear_velocity_;
    delete linear_acceleration_;
    delete angular_velocity_;
    delete linear_acceleration_vrf_;
    delete angular_velocity_vrf_;
  }
}

void Pose::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Pose::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Pose_descriptor_;
}

const Pose& Pose::default_instance() {
  protobuf_InitDefaults_pose_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<Pose> Pose_default_instance_;

Pose* Pose::New(::google::protobuf::Arena* arena) const {
  Pose* n = new Pose;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Pose::Clear() {
// @@protoc_insertion_point(message_clear_start:gnss_driver.pb.Pose)
  if (_has_bits_[0 / 32] & 255u) {
    if (has_position()) {
      if (position_ != NULL) position_->::gnss_driver::pb::PointENU::Clear();
    }
    if (has_orientation()) {
      if (orientation_ != NULL) orientation_->::gnss_driver::pb::Quaternion::Clear();
    }
    if (has_linear_velocity()) {
      if (linear_velocity_ != NULL) linear_velocity_->::gnss_driver::pb::Point3D::Clear();
    }
    if (has_linear_acceleration()) {
      if (linear_acceleration_ != NULL) linear_acceleration_->::gnss_driver::pb::Point3D::Clear();
    }
    if (has_angular_velocity()) {
      if (angular_velocity_ != NULL) angular_velocity_->::gnss_driver::pb::Point3D::Clear();
    }
    heading_ = 0;
    if (has_linear_acceleration_vrf()) {
      if (linear_acceleration_vrf_ != NULL) linear_acceleration_vrf_->::gnss_driver::pb::Point3D::Clear();
    }
    if (has_angular_velocity_vrf()) {
      if (angular_velocity_vrf_ != NULL) angular_velocity_vrf_->::gnss_driver::pb::Point3D::Clear();
    }
  }
  _has_bits_.Clear();
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Pose::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gnss_driver.pb.Pose)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .gnss_driver.pb.PointENU position = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_position()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_orientation;
        break;
      }

      // optional .gnss_driver.pb.Quaternion orientation = 2;
      case 2: {
        if (tag == 18) {
         parse_orientation:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_orientation()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_linear_velocity;
        break;
      }

      // optional .gnss_driver.pb.Point3D linear_velocity = 3;
      case 3: {
        if (tag == 26) {
         parse_linear_velocity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_linear_velocity()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_linear_acceleration;
        break;
      }

      // optional .gnss_driver.pb.Point3D linear_acceleration = 4;
      case 4: {
        if (tag == 34) {
         parse_linear_acceleration:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_linear_acceleration()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_angular_velocity;
        break;
      }

      // optional .gnss_driver.pb.Point3D angular_velocity = 5;
      case 5: {
        if (tag == 42) {
         parse_angular_velocity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_angular_velocity()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_heading;
        break;
      }

      // optional double heading = 6;
      case 6: {
        if (tag == 49) {
         parse_heading:
          set_has_heading();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &heading_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_linear_acceleration_vrf;
        break;
      }

      // optional .gnss_driver.pb.Point3D linear_acceleration_vrf = 7;
      case 7: {
        if (tag == 58) {
         parse_linear_acceleration_vrf:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_linear_acceleration_vrf()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_angular_velocity_vrf;
        break;
      }

      // optional .gnss_driver.pb.Point3D angular_velocity_vrf = 8;
      case 8: {
        if (tag == 66) {
         parse_angular_velocity_vrf:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_angular_velocity_vrf()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gnss_driver.pb.Pose)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gnss_driver.pb.Pose)
  return false;
#undef DO_
}

void Pose::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gnss_driver.pb.Pose)
  // optional .gnss_driver.pb.PointENU position = 1;
  if (has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->position_, output);
  }

  // optional .gnss_driver.pb.Quaternion orientation = 2;
  if (has_orientation()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->orientation_, output);
  }

  // optional .gnss_driver.pb.Point3D linear_velocity = 3;
  if (has_linear_velocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->linear_velocity_, output);
  }

  // optional .gnss_driver.pb.Point3D linear_acceleration = 4;
  if (has_linear_acceleration()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->linear_acceleration_, output);
  }

  // optional .gnss_driver.pb.Point3D angular_velocity = 5;
  if (has_angular_velocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->angular_velocity_, output);
  }

  // optional double heading = 6;
  if (has_heading()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->heading(), output);
  }

  // optional .gnss_driver.pb.Point3D linear_acceleration_vrf = 7;
  if (has_linear_acceleration_vrf()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, *this->linear_acceleration_vrf_, output);
  }

  // optional .gnss_driver.pb.Point3D angular_velocity_vrf = 8;
  if (has_angular_velocity_vrf()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, *this->angular_velocity_vrf_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gnss_driver.pb.Pose)
}

::google::protobuf::uint8* Pose::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:gnss_driver.pb.Pose)
  // optional .gnss_driver.pb.PointENU position = 1;
  if (has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->position_, false, target);
  }

  // optional .gnss_driver.pb.Quaternion orientation = 2;
  if (has_orientation()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->orientation_, false, target);
  }

  // optional .gnss_driver.pb.Point3D linear_velocity = 3;
  if (has_linear_velocity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->linear_velocity_, false, target);
  }

  // optional .gnss_driver.pb.Point3D linear_acceleration = 4;
  if (has_linear_acceleration()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->linear_acceleration_, false, target);
  }

  // optional .gnss_driver.pb.Point3D angular_velocity = 5;
  if (has_angular_velocity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->angular_velocity_, false, target);
  }

  // optional double heading = 6;
  if (has_heading()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->heading(), target);
  }

  // optional .gnss_driver.pb.Point3D linear_acceleration_vrf = 7;
  if (has_linear_acceleration_vrf()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        7, *this->linear_acceleration_vrf_, false, target);
  }

  // optional .gnss_driver.pb.Point3D angular_velocity_vrf = 8;
  if (has_angular_velocity_vrf()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        8, *this->angular_velocity_vrf_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gnss_driver.pb.Pose)
  return target;
}

size_t Pose::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gnss_driver.pb.Pose)
  size_t total_size = 0;

  if (_has_bits_[0 / 32] & 255u) {
    // optional .gnss_driver.pb.PointENU position = 1;
    if (has_position()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->position_);
    }

    // optional .gnss_driver.pb.Quaternion orientation = 2;
    if (has_orientation()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->orientation_);
    }

    // optional .gnss_driver.pb.Point3D linear_velocity = 3;
    if (has_linear_velocity()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->linear_velocity_);
    }

    // optional .gnss_driver.pb.Point3D linear_acceleration = 4;
    if (has_linear_acceleration()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->linear_acceleration_);
    }

    // optional .gnss_driver.pb.Point3D angular_velocity = 5;
    if (has_angular_velocity()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->angular_velocity_);
    }

    // optional double heading = 6;
    if (has_heading()) {
      total_size += 1 + 8;
    }

    // optional .gnss_driver.pb.Point3D linear_acceleration_vrf = 7;
    if (has_linear_acceleration_vrf()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->linear_acceleration_vrf_);
    }

    // optional .gnss_driver.pb.Point3D angular_velocity_vrf = 8;
    if (has_angular_velocity_vrf()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->angular_velocity_vrf_);
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Pose::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gnss_driver.pb.Pose)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Pose* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Pose>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gnss_driver.pb.Pose)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gnss_driver.pb.Pose)
    UnsafeMergeFrom(*source);
  }
}

void Pose::MergeFrom(const Pose& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gnss_driver.pb.Pose)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void Pose::UnsafeMergeFrom(const Pose& from) {
  GOOGLE_DCHECK(&from != this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_position()) {
      mutable_position()->::gnss_driver::pb::PointENU::MergeFrom(from.position());
    }
    if (from.has_orientation()) {
      mutable_orientation()->::gnss_driver::pb::Quaternion::MergeFrom(from.orientation());
    }
    if (from.has_linear_velocity()) {
      mutable_linear_velocity()->::gnss_driver::pb::Point3D::MergeFrom(from.linear_velocity());
    }
    if (from.has_linear_acceleration()) {
      mutable_linear_acceleration()->::gnss_driver::pb::Point3D::MergeFrom(from.linear_acceleration());
    }
    if (from.has_angular_velocity()) {
      mutable_angular_velocity()->::gnss_driver::pb::Point3D::MergeFrom(from.angular_velocity());
    }
    if (from.has_heading()) {
      set_heading(from.heading());
    }
    if (from.has_linear_acceleration_vrf()) {
      mutable_linear_acceleration_vrf()->::gnss_driver::pb::Point3D::MergeFrom(from.linear_acceleration_vrf());
    }
    if (from.has_angular_velocity_vrf()) {
      mutable_angular_velocity_vrf()->::gnss_driver::pb::Point3D::MergeFrom(from.angular_velocity_vrf());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::UnknownFieldSet::MergeToInternalMetdata(
      from.unknown_fields(), &_internal_metadata_);
  }
}

void Pose::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gnss_driver.pb.Pose)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Pose::CopyFrom(const Pose& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gnss_driver.pb.Pose)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool Pose::IsInitialized() const {

  return true;
}

void Pose::Swap(Pose* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Pose::InternalSwap(Pose* other) {
  std::swap(position_, other->position_);
  std::swap(orientation_, other->orientation_);
  std::swap(linear_velocity_, other->linear_velocity_);
  std::swap(linear_acceleration_, other->linear_acceleration_);
  std::swap(angular_velocity_, other->angular_velocity_);
  std::swap(heading_, other->heading_);
  std::swap(linear_acceleration_vrf_, other->linear_acceleration_vrf_);
  std::swap(angular_velocity_vrf_, other->angular_velocity_vrf_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Pose::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Pose_descriptor_;
  metadata.reflection = Pose_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Pose

// optional .gnss_driver.pb.PointENU position = 1;
bool Pose::has_position() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Pose::set_has_position() {
  _has_bits_[0] |= 0x00000001u;
}
void Pose::clear_has_position() {
  _has_bits_[0] &= ~0x00000001u;
}
void Pose::clear_position() {
  if (position_ != NULL) position_->::gnss_driver::pb::PointENU::Clear();
  clear_has_position();
}
const ::gnss_driver::pb::PointENU& Pose::position() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.position)
  return position_ != NULL ? *position_
                         : *::gnss_driver::pb::PointENU::internal_default_instance();
}
::gnss_driver::pb::PointENU* Pose::mutable_position() {
  set_has_position();
  if (position_ == NULL) {
    position_ = new ::gnss_driver::pb::PointENU;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.position)
  return position_;
}
::gnss_driver::pb::PointENU* Pose::release_position() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.position)
  clear_has_position();
  ::gnss_driver::pb::PointENU* temp = position_;
  position_ = NULL;
  return temp;
}
void Pose::set_allocated_position(::gnss_driver::pb::PointENU* position) {
  delete position_;
  position_ = position;
  if (position) {
    set_has_position();
  } else {
    clear_has_position();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.position)
}

// optional .gnss_driver.pb.Quaternion orientation = 2;
bool Pose::has_orientation() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Pose::set_has_orientation() {
  _has_bits_[0] |= 0x00000002u;
}
void Pose::clear_has_orientation() {
  _has_bits_[0] &= ~0x00000002u;
}
void Pose::clear_orientation() {
  if (orientation_ != NULL) orientation_->::gnss_driver::pb::Quaternion::Clear();
  clear_has_orientation();
}
const ::gnss_driver::pb::Quaternion& Pose::orientation() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.orientation)
  return orientation_ != NULL ? *orientation_
                         : *::gnss_driver::pb::Quaternion::internal_default_instance();
}
::gnss_driver::pb::Quaternion* Pose::mutable_orientation() {
  set_has_orientation();
  if (orientation_ == NULL) {
    orientation_ = new ::gnss_driver::pb::Quaternion;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.orientation)
  return orientation_;
}
::gnss_driver::pb::Quaternion* Pose::release_orientation() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.orientation)
  clear_has_orientation();
  ::gnss_driver::pb::Quaternion* temp = orientation_;
  orientation_ = NULL;
  return temp;
}
void Pose::set_allocated_orientation(::gnss_driver::pb::Quaternion* orientation) {
  delete orientation_;
  orientation_ = orientation;
  if (orientation) {
    set_has_orientation();
  } else {
    clear_has_orientation();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.orientation)
}

// optional .gnss_driver.pb.Point3D linear_velocity = 3;
bool Pose::has_linear_velocity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Pose::set_has_linear_velocity() {
  _has_bits_[0] |= 0x00000004u;
}
void Pose::clear_has_linear_velocity() {
  _has_bits_[0] &= ~0x00000004u;
}
void Pose::clear_linear_velocity() {
  if (linear_velocity_ != NULL) linear_velocity_->::gnss_driver::pb::Point3D::Clear();
  clear_has_linear_velocity();
}
const ::gnss_driver::pb::Point3D& Pose::linear_velocity() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.linear_velocity)
  return linear_velocity_ != NULL ? *linear_velocity_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
::gnss_driver::pb::Point3D* Pose::mutable_linear_velocity() {
  set_has_linear_velocity();
  if (linear_velocity_ == NULL) {
    linear_velocity_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.linear_velocity)
  return linear_velocity_;
}
::gnss_driver::pb::Point3D* Pose::release_linear_velocity() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.linear_velocity)
  clear_has_linear_velocity();
  ::gnss_driver::pb::Point3D* temp = linear_velocity_;
  linear_velocity_ = NULL;
  return temp;
}
void Pose::set_allocated_linear_velocity(::gnss_driver::pb::Point3D* linear_velocity) {
  delete linear_velocity_;
  linear_velocity_ = linear_velocity;
  if (linear_velocity) {
    set_has_linear_velocity();
  } else {
    clear_has_linear_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.linear_velocity)
}

// optional .gnss_driver.pb.Point3D linear_acceleration = 4;
bool Pose::has_linear_acceleration() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void Pose::set_has_linear_acceleration() {
  _has_bits_[0] |= 0x00000008u;
}
void Pose::clear_has_linear_acceleration() {
  _has_bits_[0] &= ~0x00000008u;
}
void Pose::clear_linear_acceleration() {
  if (linear_acceleration_ != NULL) linear_acceleration_->::gnss_driver::pb::Point3D::Clear();
  clear_has_linear_acceleration();
}
const ::gnss_driver::pb::Point3D& Pose::linear_acceleration() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.linear_acceleration)
  return linear_acceleration_ != NULL ? *linear_acceleration_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
::gnss_driver::pb::Point3D* Pose::mutable_linear_acceleration() {
  set_has_linear_acceleration();
  if (linear_acceleration_ == NULL) {
    linear_acceleration_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.linear_acceleration)
  return linear_acceleration_;
}
::gnss_driver::pb::Point3D* Pose::release_linear_acceleration() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.linear_acceleration)
  clear_has_linear_acceleration();
  ::gnss_driver::pb::Point3D* temp = linear_acceleration_;
  linear_acceleration_ = NULL;
  return temp;
}
void Pose::set_allocated_linear_acceleration(::gnss_driver::pb::Point3D* linear_acceleration) {
  delete linear_acceleration_;
  linear_acceleration_ = linear_acceleration;
  if (linear_acceleration) {
    set_has_linear_acceleration();
  } else {
    clear_has_linear_acceleration();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.linear_acceleration)
}

// optional .gnss_driver.pb.Point3D angular_velocity = 5;
bool Pose::has_angular_velocity() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void Pose::set_has_angular_velocity() {
  _has_bits_[0] |= 0x00000010u;
}
void Pose::clear_has_angular_velocity() {
  _has_bits_[0] &= ~0x00000010u;
}
void Pose::clear_angular_velocity() {
  if (angular_velocity_ != NULL) angular_velocity_->::gnss_driver::pb::Point3D::Clear();
  clear_has_angular_velocity();
}
const ::gnss_driver::pb::Point3D& Pose::angular_velocity() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.angular_velocity)
  return angular_velocity_ != NULL ? *angular_velocity_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
::gnss_driver::pb::Point3D* Pose::mutable_angular_velocity() {
  set_has_angular_velocity();
  if (angular_velocity_ == NULL) {
    angular_velocity_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.angular_velocity)
  return angular_velocity_;
}
::gnss_driver::pb::Point3D* Pose::release_angular_velocity() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.angular_velocity)
  clear_has_angular_velocity();
  ::gnss_driver::pb::Point3D* temp = angular_velocity_;
  angular_velocity_ = NULL;
  return temp;
}
void Pose::set_allocated_angular_velocity(::gnss_driver::pb::Point3D* angular_velocity) {
  delete angular_velocity_;
  angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    set_has_angular_velocity();
  } else {
    clear_has_angular_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.angular_velocity)
}

// optional double heading = 6;
bool Pose::has_heading() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void Pose::set_has_heading() {
  _has_bits_[0] |= 0x00000020u;
}
void Pose::clear_has_heading() {
  _has_bits_[0] &= ~0x00000020u;
}
void Pose::clear_heading() {
  heading_ = 0;
  clear_has_heading();
}
double Pose::heading() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.heading)
  return heading_;
}
void Pose::set_heading(double value) {
  set_has_heading();
  heading_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Pose.heading)
}

// optional .gnss_driver.pb.Point3D linear_acceleration_vrf = 7;
bool Pose::has_linear_acceleration_vrf() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void Pose::set_has_linear_acceleration_vrf() {
  _has_bits_[0] |= 0x00000040u;
}
void Pose::clear_has_linear_acceleration_vrf() {
  _has_bits_[0] &= ~0x00000040u;
}
void Pose::clear_linear_acceleration_vrf() {
  if (linear_acceleration_vrf_ != NULL) linear_acceleration_vrf_->::gnss_driver::pb::Point3D::Clear();
  clear_has_linear_acceleration_vrf();
}
const ::gnss_driver::pb::Point3D& Pose::linear_acceleration_vrf() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.linear_acceleration_vrf)
  return linear_acceleration_vrf_ != NULL ? *linear_acceleration_vrf_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
::gnss_driver::pb::Point3D* Pose::mutable_linear_acceleration_vrf() {
  set_has_linear_acceleration_vrf();
  if (linear_acceleration_vrf_ == NULL) {
    linear_acceleration_vrf_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.linear_acceleration_vrf)
  return linear_acceleration_vrf_;
}
::gnss_driver::pb::Point3D* Pose::release_linear_acceleration_vrf() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.linear_acceleration_vrf)
  clear_has_linear_acceleration_vrf();
  ::gnss_driver::pb::Point3D* temp = linear_acceleration_vrf_;
  linear_acceleration_vrf_ = NULL;
  return temp;
}
void Pose::set_allocated_linear_acceleration_vrf(::gnss_driver::pb::Point3D* linear_acceleration_vrf) {
  delete linear_acceleration_vrf_;
  linear_acceleration_vrf_ = linear_acceleration_vrf;
  if (linear_acceleration_vrf) {
    set_has_linear_acceleration_vrf();
  } else {
    clear_has_linear_acceleration_vrf();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.linear_acceleration_vrf)
}

// optional .gnss_driver.pb.Point3D angular_velocity_vrf = 8;
bool Pose::has_angular_velocity_vrf() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void Pose::set_has_angular_velocity_vrf() {
  _has_bits_[0] |= 0x00000080u;
}
void Pose::clear_has_angular_velocity_vrf() {
  _has_bits_[0] &= ~0x00000080u;
}
void Pose::clear_angular_velocity_vrf() {
  if (angular_velocity_vrf_ != NULL) angular_velocity_vrf_->::gnss_driver::pb::Point3D::Clear();
  clear_has_angular_velocity_vrf();
}
const ::gnss_driver::pb::Point3D& Pose::angular_velocity_vrf() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Pose.angular_velocity_vrf)
  return angular_velocity_vrf_ != NULL ? *angular_velocity_vrf_
                         : *::gnss_driver::pb::Point3D::internal_default_instance();
}
::gnss_driver::pb::Point3D* Pose::mutable_angular_velocity_vrf() {
  set_has_angular_velocity_vrf();
  if (angular_velocity_vrf_ == NULL) {
    angular_velocity_vrf_ = new ::gnss_driver::pb::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Pose.angular_velocity_vrf)
  return angular_velocity_vrf_;
}
::gnss_driver::pb::Point3D* Pose::release_angular_velocity_vrf() {
  // @@protoc_insertion_point(field_release:gnss_driver.pb.Pose.angular_velocity_vrf)
  clear_has_angular_velocity_vrf();
  ::gnss_driver::pb::Point3D* temp = angular_velocity_vrf_;
  angular_velocity_vrf_ = NULL;
  return temp;
}
void Pose::set_allocated_angular_velocity_vrf(::gnss_driver::pb::Point3D* angular_velocity_vrf) {
  delete angular_velocity_vrf_;
  angular_velocity_vrf_ = angular_velocity_vrf;
  if (angular_velocity_vrf) {
    set_has_angular_velocity_vrf();
  } else {
    clear_has_angular_velocity_vrf();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Pose.angular_velocity_vrf)
}

inline const Pose* Pose::internal_default_instance() {
  return &Pose_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace gnss_driver

// @@protoc_insertion_point(global_scope)
